# Shell
shell zsh

# Window behavior
confirm_os_window_close 0
dynamic_background_opacity yes
background_opacity 0.8
background_blur 1
enable_audio_bell no
mouse_hide_wait -1

# window_padding_width 10

# Font
font_family      JetBrainsMonoNerdFont
font_size        12

# Theme
include current-theme.conf

# Keybindings
clear_all_shortcuts yes

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

map ctrl+shift+t new_tab
map ctrl+shift+right next_tab
map ctrl+shift+left  previous_tab

map ctrl+shift+q close_window
