#basic settings
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on

unbind C-b
set -g prefix C-q
bind-key C-q send-prefix

unbind %
bind v split-window -h -c "#{pane_current_path}"
unbind '"'
bind s split-window -v -c "#{pane_current_path}"

unbind r
bind r source-file $HOME/.config/tmux/tmux.conf

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind & select-window -t 1
bind é select-window -t 2
bind \" select-window -t 3
bind \' select-window -t 4
bind ( select-window -t 5
bind - select-window -t 6
bind è select-window -t 7
bind _ select-window -t 8
bind ç select-window -t 9
bind à select-window -t 10

set -g status-bg "#B289F5"
set -g status-fg "#FCF6FE"
